library(dplyr)
library(stringr)
library(ggplot2)
library(leaflet)
library(googleVis)
library(maps)
library(shiny)
library(DT)
library(data.table)
library(shinydashboard)
library(geojsonio)
library(rgeos)
library(rgdal)
library(sp)
library(sf)
library(shinythemes)
library(RColorBrewer)

bikepathgeo <- geojson_read('./Bicycle_Routes.geojson',what = 'sp')
boroboundary <- geojson_read('./Borough_Boundaries.geojson', what = 'sp')
bikepriority <- geojson_read('./VZV_Bike_Priority_Areas.geojson', what = 'sp')
AccReason <- fread('./accreason.csv')
Kcrash <- fread('./Kcrash.csv')
Mcrash <- fread('./Mcrash.csv')
Qcrash <- fread('./Qcrash.csv')
Scrash <- fread('./Scrash.csv')
Xcrash <- fread('./Xcrash.csv')
