library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(leaflet)
library(googleVis)
library(maps)
library(shiny)
library(shinydashboard)
library(shinythemes)
library(RColorBrewer)
library(data.table)
library(DT)
library(geojsonio)
library(rgeos)
library(rgdal)
library(sp)
library(sf)


# bikepathgeo <- geojson_read('./Bicycle_Routes.geojson',what = 'sp')
# boroboundary <- geojson_read('./Borough_Boundaries.geojson', what = 'sp')
bikepriority <- geojson_read('./VZV_Bike_Priority_Areas.geojson', what = 'sp')
senior <- geojson_read('./VZV_Safe_Streets_for_Seniors.geojson',what = 'sp')
neighborhood <- geojson_read('./VZV_Neighborhood_Slow_Zones.geojson',what = 'sp')
EnhancedCrossing <- read.csv('./VZV_Enhanced_Crossings_20191001.csv', stringsAsFactors = F)
AccReason <- fread('./accreason.csv', stringsAsFactors = F)
Kcrash <- fread('./Kcrash.csv', stringsAsFactors = F)
Mcrash <- fread('./Mcrash.csv', stringsAsFactors = F)
Qcrash <- fread('./Qcrash.csv', stringsAsFactors = F)
Scrash <- fread('./Scrash.csv', stringsAsFactors = F)
Xcrash <- fread('./Xcrash.csv', stringsAsFactors = F)

